name: re4ctor-ci
on:
  push:
    branches: [ main, master ]
    tags: [ "v*" ]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev python3
      - name: Build (if Makefile present)
        run: |
          if [ -f Makefile ]; then
            make -j
          else
            echo "No Makefile; skipping build."
          fi
      - name: Tamper test (if client exists)
        run: |
          if [ -x tests/tamper.sh ]; then
            bash -x tests/tamper.sh
          else
            echo "No tests/tamper.sh; skipping tamper test."
          fi
      - name: Pack artifacts (if built)
        run: |
          mkdir -p dist
          if [ -d bin ] || [ -d lib ]; then
            mkdir -p dist && tar czf dist/r4-bundle-linux-amd64.tar.gz bin lib include 2>/dev/null || true
            (cd dist && sha256sum r4-bundle-linux-amd64.tar.gz > SHA256SUMS) || true
          else
            echo "No bin/lib to package."
          fi
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: r4-bundle
          path: dist/
