name: CI
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Prepare dummy re4_stream (quiet, no SIGPIPE)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p tools
          cat > tools/re4_stream_dummy <<'SH'
          #!/usr/bin/env bash
          set +e
          trap '' PIPE
          exec cat /dev/zero 2>/dev/null
          SH
          chmod +x tools/re4_stream_dummy
          echo "$PWD/tools" >> "$GITHUB_PATH"

      - name: Export R4 env
        shell: bash
        run: |
          echo "R4_PATH=${GITHUB_WORKSPACE}/tools/re4_stream_dummy" >> "$GITHUB_ENV"
          echo "R4_SEED=1" >> "$GITHUB_ENV"

      - name: Build CLI
        shell: bash
        run: make -B r4cs_cat

      - name: Smoke – hex 64B
        shell: bash
        run: |
          set -euo pipefail
          ./r4cs_cat -n 64 -hex | tee out.hex
          grep -Eq '^[0-9a-f]{128}$' out.hex

      - name: Smoke – determinism (4096B)
        shell: bash
        continue-on-error: true
        run: |
          set -euo pipefail
          ./r4cs_cat -n 4096 > a.bin
          ./r4cs_cat -n 4096 > b.bin
          if cmp -s a.bin b.bin; then
            echo "determinism OK"
          else
            echo "::warning::determinism mismatch (allowed for now)"
          fi
