name: public-sanity

"on":
  push:
    branches: [main]
  pull_request:

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "starting public sanity pass"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo state
        run: |
          echo "[git status]"
          git status
          echo "[tree]"
          ls -R .

      - name: Verify README exists
        run: |
          test -s README.md
          echo "README.md present ✅"

      - name: Verify selftest wiring exists
        run: |
          test -s packages/core/selftest/fips_selftest.py
          test -s packages/core/selftest/manifest.json
          echo "selftest bundle present ✅"

      - name: Verify Docker scaffolding present
        run: |
          test -s packages/core/docker/Dockerfile
          test -s packages/core/docker/main.py
          echo "docker runtime present ✅"

      - name: Verify proof summaries exist
        run: |
          test -s packages/core/proof/dieharder/summary-2025-01.txt
          echo "proof summaries present ✅"

      - name: Python lint (API surface only)
        run: |
          python3 -m py_compile packages/core/docker/main.py
          echo "main.py bytecode compiled ✅"

      - name: Install API runtime deps
        run: |
          python3 -m pip install --upgrade pip
          pip install fastapi uvicorn
          echo "fastapi + uvicorn installed ✅"

      - name: Basic import check
        run: |
          python3 -c "import sys; sys.path.append('packages/core/docker'); import main as r4api; print('[OK] imported main.py from docker image layout ✅')"  # yamllint disable-line rule:line-length  # yamllint disable-line rule:line-length

      - name: Emit status
        run: echo "✅ public-sanity done"
