name: public-sanity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo state
        run: |
          echo "=== git ls-tree ==="
          git ls-tree -r --name-only HEAD | sed 's/^/    /'
          echo
          echo "=== top-level ==="
          ls -R .

      - name: Verify README exists
        run: |
          test -s README.md
          echo "[OK] README.md present and non-empty"

      - name: Verify selftest wiring exists
        run: |
          test -s packages/core/selftest/fips_selftest.py
          test -s packages/core/selftest/manifest.json
          echo "[OK] selftest files present"

      - name: Verify Docker scaffolding present
        run: |
          test -s packages/core/docker/Dockerfile
          test -s packages/core/docker/main.py
          echo "[OK] Docker runtime present"

      - name: Verify proof summaries exist
        run: |
          test -s packages/core/proof/dieharder/summary-2025-01.txt
          test -s packages/core/proof/practrand/summary-2025-01.txt
          test -s packages/core/proof/bigcrush/summary-2025-01.txt
          echo "[OK] proof summaries present"

      - name: Python lint (API surface only)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Basic import check
        run: |
          python3 -c "import sys; sys.path.append('packages/core/docker'); import main as r4api; print('[OK] imported main.py from docker image layout')"

      - name: Emit status
        run: |
          echo "public-sanity: PASS ✅"
